version: "3.8"
services:
  db:
    image: postgres:15
    restart: no
    environment:
      POSTGRES_USER: biteapp
      POSTGRES_PASSWORD: superburrito
      POSTGRES_DB: bite_tracker
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

