// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Meal struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	MealTypeID  string
	TimeOfMeal  time.Time
	Description string
	HungerLevel int32
	Symptoms    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MealType struct {
	ID        string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MealsCatalog struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	TimesUsed   int32
	Description string
	MealTypeID  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
