// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Meal struct {
	ID          uuid.UUID
	UserID      pgtype.UUID
	MealType    string
	TimeOfMeal  time.Time
	Description string
	HungerLevel int32
	Symptoms    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Username  pgtype.Text
	FirstName pgtype.Text
	LastName  pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}
