// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Meal struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	MealType    string
	TimeOfMeal  time.Time
	Description string
	HungerLevel int32
	Symptoms    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Username  *string
	FirstName *string
	LastName  *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
