// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (
  user_id,
  meal_type,
  time_of_meal,
  description,
  hunger_level,
  symptoms
) VALUES (
  $1,$2,$3,$4,$5,$6
)
RETURNING id, user_id, meal_type, time_of_meal, description, hunger_level, symptoms, created_at, updated_at
`

type CreateMealParams struct {
	UserID      uuid.UUID
	MealType    string
	TimeOfMeal  time.Time
	Description string
	HungerLevel int32
	Symptoms    []string
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.UserID,
		arg.MealType,
		arg.TimeOfMeal,
		arg.Description,
		arg.HungerLevel,
		arg.Symptoms,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealType,
		&i.TimeOfMeal,
		&i.Description,
		&i.HungerLevel,
		&i.Symptoms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT  FROM user
WHERE u.username = $1::text
LIMIT 1
`

type GetUserRow struct {
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan()
	return i, err
}

const listMealsByUsernameAndDate = `-- name: ListMealsByUsernameAndDate :many
SELECT id, user_id, meal_type, time_of_meal, description, hunger_level, symptoms, created_at, updated_at FROM meals
WHERE user_id = $1 AND
	time_of_meal > $2 AND time_of_meal < ( ($2) + interval '1 day' )
ORDER BY time_of_meal
`

type ListMealsByUsernameAndDateParams struct {
	UserID  uuid.UUID
	ForDate time.Time
}

func (q *Queries) ListMealsByUsernameAndDate(ctx context.Context, arg ListMealsByUsernameAndDateParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsByUsernameAndDate, arg.UserID, arg.ForDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MealType,
			&i.TimeOfMeal,
			&i.Description,
			&i.HungerLevel,
			&i.Symptoms,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeal = `-- name: UpdateMeal :exec
UPDATE meals
  SET meal_type = $2,
  time_of_meal = $3,
  description = $4,
  hunger_level = $5,
  symptoms = $6,
  updated_at = $7
WHERE id = $1
`

type UpdateMealParams struct {
	ID          uuid.UUID
	MealType    string
	TimeOfMeal  time.Time
	Description string
	HungerLevel int32
	Symptoms    []string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.Exec(ctx, updateMeal,
		arg.ID,
		arg.MealType,
		arg.TimeOfMeal,
		arg.Description,
		arg.HungerLevel,
		arg.Symptoms,
		arg.UpdatedAt,
	)
	return err
}
