// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meal struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	MealType    string
	TimeOfMeal  pgtype.Timestamptz
	Description string
	HungerLevel pgtype.Int4
	Symptoms    []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
