CREATE ROLE bt_app_user WITH LOGIN PASSWORD :bt_app_user_password;
GRANT CONNECT ON DATABASE bite_tracker TO bt_app_user;
GRANT USAGE ON SCHEMA public TO bt_app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO bt_app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO bt_app_user;

CREATE ROLE bt_migrate_user WITH LOGIN PASSWORD :bt_migrate_user_password;
GRANT CONNECT ON DATABASE bite_tracker TO bt_migrate_user;
GRANT CREATE, USAGE ON SCHEMA public TO bt_migrate_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO bt_migrate_user;
