// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddMeal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section\"><div class=\"container\"><h1 class=\"title\">Add Meal</h1><div class=\"field\"><label class=\"label\" for=\"date\">Date</label> <input x-data x-init=\"$el.focus()\" class=\"input\" type=\"date\" id=\"date\" name=\"date\" value=\"1.1.2025\"></div><div class=\"field\"><label class=\"label\" for=\"time\">Time</label> <input class=\"input\" type=\"time\" id=\"time\" name=\"time\" value=\"15:54\"></div><div class=\"field\" x-data='{ meal: \"\" }'><label class=\"label\" for=\"meal\">Meal</label> <input class=\"input\" type=\"text\" id=\"meal\" name=\"meal\" placeholder=\"Type or pick below\" x-model=\"meal\"><div class=\"tags mt-2\"><button class=\"tag\" x-on:click=\"meal='Chicken Rice'\">Chicken Rice</button> <button class=\"tag\" x-on:click=\"meal='Oatmeal'\">Oatmeal</button> <button class=\"tag\" x-on:click=\"meal='Salad'\">Salad</button></div></div><div class=\"field\" x-data=\"{ range: 4 }\"><label class=\"label\" for=\"hunger\">Hunger Level (1-not hungry, 5-starving)</label><div class=\"field has-addons\"><div class=\"control\"><input class=\"input\" type=\"range\" x-model=\"range\" min=\"1\" max=\"5\" id=\"hunger\" name=\"hunger\"></div><div class=\"control\"><span class=\"button is-dark\" x-text=\"range\"></span></div></div></div><div class=\"field\"><label class=\"label\" for=\"symptoms\">Symptoms</label><div class=\"tags mt-2\"><button class=\"tag\">Bloating</button> <button class=\"tag\">Gas</button> <button class=\"tag\">Acid</button> <button class=\"tag\">Full</button></div></div><div class=\"field is-grouped pt-5\"><div class=\"control\"><button class=\"button is-primary\">Submit</button></div><div class=\"control\" hx-boost=\"true\"><a class=\"button is-primary is-light\" href=\"/\">Cancel</a></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
